=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Ejercicio 1/ejercicio1.dtd
<!ELEMENT persona (nombre,ocupacion,aficiones,direccion,telefono)>
<!ELEMENT nombre (nombre_pila,apellido+)>
<!ATTLIST nombre DNI  CDATA #REQUIRED>
<!ELEMENT nombre_pila (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT ocupacion (#PCDATA)>
<!ELEMENT aficiones (aficion+)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Ejercicio 1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona SYSTEM "ejercicio1.dtd">
<persona >
        <nombre DNI="416455">
            <nombre_pila>Adrian</nombre_pila>
            <apellido>Aguilar</apellido>
        </nombre>
        <ocupacion>Hago como que estudio</ocupacion>
        <aficiones>
          <aficion>Viciar</aficion>        
        </aficiones>
        <direccion>Mi casa</direccion>
        <telefono>55555555</telefono>
</persona>
