=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Andal_Aaron/exp.dtd
<!ELEMENT mejores_expedientes (curso, nominstituto, ciclos)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT nominstituto (#PCDATA)>
<!ELEMENT ciclos (ciclo+)>
<!ELEMENT ciclo (nom, alumne+)>
<!ATTLIST ciclo tutor ID #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT alumne (dades_personals+, dades_academiques+)>
<!ELEMENT dades_personals (nomapellido, dni, correo, telefono)>
<!ATTLIST dni identificador NMTOKEN #IMPLIED>
<!ELEMENT nomapellido (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT dades_academiques (moduls+, tutor, nota_media)>
<!ELEMENT moduls (modul)>
<!ATTLIST modul nom ID #REQUIRED nota ID #REQUIRED>
<!ELEMENT tutor (#PCDATA)>
<!ATTLIST tutor idtutor IDREFS #REQUIRED>
<!ELEMENT nota_media (#PCDATA)>
<!ATTLIST document versio CDATA #FIXED "1.0">
<!ATTLIST document codificacio NMTOKEN #DEFAULT "UTF-8">

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Andal_Aaron/MejorExp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE expedientes SYSTEM "exp.dtd">

<mejores_expedientes>
 <curso>2015-2016</curso>
 <nominstituto>IES Proven</nominstituto>
 <ciclos>
    <ciclo tutor="Dani_Molla">
      <nom>DAW</nom>
      <alumne>
        <dades_personals>
          <nomapellido>Aaron Andal</nomapellido>
          <dni>347856785Y</dni>
          <correo>aaronandal@gmail.com</correo>
          <telefono></telefono>
        </dades_personals>
        <dades_academiques>
          <moduls>
            <modul nom="M04" nota="10" />
          </moduls>
          <tutor idtutor="Dani_Molla"></tutor>
          <nota_media></nota_media>
        </dades_academiques>
      </alumne>
    </ciclo>
  </ciclos>

 <ciclos>
    <ciclo tutor="Anakin_Skywalker">
      <nom>DAM</nom>
      <alumne>
        <dades_personals>
          <nomapellido>Luke Skywalker</nomapellido>
          <correo>lukeskywalker@gmail.com</correo>
          <telefono></telefono>
        </dades_personals>
        <dades_academiques>
          <moduls>
            <modul nom="M08" nota="10" />
          </moduls>
          <tutor idtutor="Anakin Skywalker"></tutor>
          <nota_media></nota_media>
        </dades_academiques>
      </alumne>
    </ciclo>
  </ciclos>

 <ciclos>
    <ciclo tutor="Qui_Gon">
      <nom>ASIX</nom>
      <alumne>
        <dades_personals>
          <nomapellido>Obi Wan</nomapellido>
          <correo>obiwan@gmail.com</correo>
          <telefono></telefono>
        </dades_personals>
        <dades_academiques>
          <moduls>
            <modul nom="M02" nota="10" />
          </moduls>
          <tutor idtutor="Qui_Gon"></tutor>
          <nota_media></nota_media>
        </dades_academiques>
      </alumne>
    </ciclo>
  </ciclos>

 <ciclos>
    <ciclo tutor="Darth_Vader">
      <nom>DAM</nom>
      <alumne>
        <dades_personals>
          <nomapellido>Kylo Ren</nomapellido>
          <correo>kyloren@gmail.com</correo>
          <telefono></telefono>
        </dades_personals>
        <dades_academiques>
          <moduls>
            <modul nom="M04" nota="10" />
          </moduls>
          <tutor idtutor="Darth_Vader"></tutor>
          <nota_media></nota_media>
        </dades_academiques>
      </alumne>
    </ciclo>
  </ciclos>

</mejores_expedientes>
