=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Ejercicio 5/ejercicio5.dtd
<!ELEMENT receta (nombre_plato,fotografia?,ingredientes,pasos)>
<!ENTITY foto1 SYSTEM "imagen1.jpg" NDATA JPG>
<!ENTITY foto2 SYSTEM "imagen2.jpg" NDATA JPG>

<!ELEMENT nombre_plato (#PCDATA)>
<!ELEMENT fotografia (#PCDATA)>
<!NOTATION JPG SYSTEM "image/jpeg">

<!ATTLIST fotografia foto ENTITIES #IMPLIED>

<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>

<!ELEMENT pasos (paso+)>

<!ATTLIST paso orden CDATA #REQUIRED>

<!ELEMENT paso (#PCDATA)>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Ejercicio 5/ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta SYSTEM "ejercicio5.dtd">

<receta>
<nombre_plato>Paella</nombre_plato>
<fotografia foto="foto1 foto2"></fotografia>

<ingredientes>
<ingrediente>Arroz</ingrediente>

</ingredientes>

<pasos>

<paso orden="1">lol1</paso>

<paso orden="2">lol2</paso>


</pasos>

</receta>
