=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/ExamenXSD/Andal_Aaron/Exercici 2/libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="libros">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libreria" type="tlibreria" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

  <xs:complexType name="tlibreria">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string" />
      <xs:element name="libro" type="tlibro" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tlibro">
    <xs:sequence>
      <xs:element name="codigo" type="tcodigo" />
      <xs:element name="titulo" type="xs:string" />
      <xs:element name="nivel" type="xs:string" />
      <xs:element name="autor" type="tautor" />
      <xs:element name="editorial" type="teditorial" />
      <xs:element name="fecha_publicacion" type="xs:date" minOccurs="0" maxOccurs="2"/>
    </xs:sequence>
  </xs:complexType>

<xs:simpleType name="tcodigo"> // Se define fuera para que sea más legible
  <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{8}"/> // Hasta 8 veces y del 0 al 9
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tautor"> // Se define fuera para que sea más legible
  <xs:restriction base="xs:string">
    <xs:maxInclusive value="50" />
    <xs:minInclusive value="1" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="teditorial"> // Se define fuera para que sea más legible
  <xs:restriction base="xs:string">
    <xs:maxInclusive value="50" />
    <xs:minInclusive value="1" />
  </xs:restriction>
</xs:simpleType>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/ExamenXSD/Andal_Aaron/Exercici 2/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libros.xsd">
      <libreria>
          <nombre>Abacus</nombre>
          <libro>
                <codigo>1-AZ-123</codigo>
                <titulo>Curso de XML</titulo>
                <nivel grado="1">Basico</nivel>
                <autor>Gregorio Martin</autor>
                <editorial>Ra-Ma Editorial</editorial>
                <fecha_publicacion>2014-01-31</fecha_publicacion>
            </libro>
            <libro>
                <codigo>0-AA-000</codigo>
                <titulo>XML (Edicion revisada y ampliada)</titulo>
                <nivel grado="6">Medio</nivel>
                <autor>Oscar Gonzalez</autor>
                <editorial>Editorial Planeta</editorial>
            </libro>
      </libreria>
      <libreria>
          <nombre>La casa del libro</nombre>
          <libro>
                <codigo>9-ZZ-999</codigo>
                <titulo>XML: bases esenciales, conceptos y casos practicos</titulo>
                <nivel grado="9">Avanzado</nivel>
                <autor>Juan Diego Gutierrez Gallardo</autor>
                <editorial> Grupo Anaya</editorial>
                <fecha_publicacion>2015-12-01</fecha_publicacion>
          </libro>
      </libreria>
</libros>
