=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/ExamenMarcasXML/Exercici 2/junta.dtd
<!ELEMENT junta (persona+)>
<!ATTLIST persona nom CDATA #REQUIRED cognom CDATA #REQUIRED>
<!ATTLIST persona carrec ID #REQUIRED>
<!ELEMENT persona (portal, codi_cc)>
<!ATTLIST portal num[1|2|3|4|5]>
<!ELEMENT portal (pis, lletra)>
<!ELEMENT pis (#PCDATA)>
<!ELEMENT lletra (#PCDATA)>
<!ELEMENT codi_cc (#PCDATA)>
<!ATTLIST persona codi_cc ID #REQUIRED>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/ExamenMarcasXML/Exercici 2/junta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE junta SYSTEM "junta.dtd" >
<junta>
  <persona nom="Luke" cognom="Skywalker" carrec="President">
    <portal num="1">
      <pis>5</pis>
      <lletra>A</lletra>
    </portal>
    <codi_cc id_cc="A8X" >1026996541Y</codi_cc>
  </persona>

  <persona nom="Darth" cognom="Vader" carrec="Vice President">
    <portal num="2">
      <pis>3</pis>
      <lletra>B</lletra>
    </portal>
    <codi_cc id_cc="A9X">1027896541T</codi_cc>
  </persona>

  <persona nom="Han" cognom="Solo" carrec="Secretari">
    <portal num="3">
      <pis>8</pis>
      <lletra>Z</lletra>
    </portal>
    <codi_cc >2345996541S</codi_cc>
  </persona>

  <persona nom="Leia" cognom="Organa" carrec="Vocal">
    <portal num="4">
      <pis>10</pis>
      <lletra>B</lletra>
    </portal>
    <codi_cc id_cc="A10X">3657896541C</codi_cc>
  </persona>

  <persona nom="Obi Wan" cognom="Kenobi" carrec="Cap">
    <portal num="5">
      <pis>8</pis>
      <lletra>Y</lletra>
    </portal>
    <codi_cc id_cc="A11X">4557896987B</codi_cc>
  </persona>
</junta>
