=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/DTD/DTD/test1dtd.dtd
<!ELEMENT comanda (client, articles, total)>
<!ATTLIST comanda numero NMTOKEN #REQUIRED>
<!ATTLIST comanda dia CDATA #REQUIRED>

<!ELEMENT client (nom, cognom?)>
<!ATTLIST client codi NMTOKEN #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>

<!ELEMENT articles (article+)>
<!ELEMENT article (descripciÃ³, quantitat, preu)>
<!ELEMENT descripciÃ³ (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT preu (#PCDATA)>

<!ELEMENT total EMPTY>
<!ATTLIST total valor CDATA #REQUIRED>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/DTD/DTD/Test1dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda SYSTEM "test1dtd.dtd">

<comanda numero="26" dia="2011−12−01">

  <client codi="20">
    <nom>Frederic</nom>
    <cognom>Garcia</cognom>
  </client>
  
  <articles>
    <article>
     <descripció>Yoda Mimobot USB Flash Drive 8GB</descripció>
      <quantitat>5</quantitat>
      <preu>38.99</preu>
    </article>
    
    <article>
      <descripció>Darth Vader Half Helmet Case for iPhone</descripció>
      <quantitat>2</quantitat>
      <preu>29.95</preu>
    </article>
  </articles>

  <total valor="254,85"/>
</comanda>
