=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/SCHEMA XSD/XML_XSD_Exemples/versio1/agenda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:simpleType    name="any_naixement">
  <xs:restriction base="xs:integer">
    <xs:maxInclusive value="2015"/>
    <xs:minInclusive value="1850"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="persona">
    <xs:sequence>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="cognoms" type="xs:string"/>
        <xs:element name="naixement" type="any_naixement"/>
    </xs:sequence> 
</xs:complexType>
  
  <xs:element name="agenda">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contacte" type="persona" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/SCHEMA XSD/XML_XSD_Exemples/versio1/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="agenda.xsd">
  <contacte>
    <nom></nom>  
    <cognoms></cognoms>
    <naixement>1994</naixement>
  </contacte>
  <contacte>
    <nom></nom>
    <cognoms></cognoms>
    <naixement>1850</naixement>
  </contacte>
</agenda>
