=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Ejercicio 4/sis_nacions.dtd
<!ELEMENT sis_nacions (dia+)>
<!ELEMENT dia (partido+)>
<!ATTLIST  dia round CDATA #REQUIRED>
<!ELEMENT partido (equipo+)>
<!ATTLIST  partido numero CDATA #REQUIRED>
<!ELEMENT equipo (nombre_equipo,puntos)>
<!ELEMENT puntos (anotadores+)>
<!ELEMENT anotadores (nom,cognoms,puntos_totales)>
<!ATTLIST  anotadores jugador CDATA #REQUIRED>
<!ELEMENT puntos_totales (try,try_penal,drop_penal,goal,convercion)>

<!ELEMENT nombre_equipo (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognoms (#PCDATA)>
<!ELEMENT try (#PCDATA)>
<!ELEMENT try_penal (#PCDATA)>
<!ELEMENT drop_penal (#PCDATA)>
<!ELEMENT goal (#PCDATA)>
<!ELEMENT convercion (#PCDATA)>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Ejercicio 4/sis_nacions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sis_nacions SYSTEM "sis_nacions.dtd">
<sis_nacions>
  <dia round="1">
    <partido numero="1">
      <equipo>
          <nombre_equipo></nombre_equipo>
          <puntos>
            <anotadores jugador="1">
              <nom></nom>
              <cognoms></cognoms>
              <puntos_totales>
                <try></try>
                <try_penal></try_penal>
                <drop_penal></drop_penal>
                <goal></goal>
                <convercion></convercion>
              </puntos_totales>
            </anotadores>
          </puntos>      
      </equipo>
      
      <equipo>
          <nombre_equipo></nombre_equipo>
          <puntos>
            <anotadores jugador="1">
              <nom></nom>
              <cognoms></cognoms>
              <puntos_totales>
                <try></try>
                <try_penal></try_penal>
                <drop_penal></drop_penal>
                <goal></goal>
                <convercion></convercion>
              </puntos_totales>
            </anotadores>
          </puntos>     
      </equipo>    
    </partido>
  </dia>
</sis_nacions>
