=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Ejercicio 3/jugador.dtd
<!ELEMENT jugador (dades_personals,fitxa_tecnica,estadistiques+)>

<!ELEMENT dades_personals (nom,cognoms)>
<!ELEMENT fitxa_tecnica (equip,posicio+,dorsal)>
<!ELEMENT estadistiques (convocat,minuts_jugats,gols)>

<!ATTLIST  estadistiques jornada CDATA #REQUIRED>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognoms (#PCDATA)>
<!ELEMENT equip (#PCDATA)>
<!ELEMENT posicio (#PCDATA)>
<!ELEMENT dorsal (#PCDATA)>
<!ELEMENT convocat (#PCDATA)>
<!ELEMENT minuts_jugats (#PCDATA)>
<!ELEMENT gols (#PCDATA)>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/Ejercicio 3/jugadors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jugador SYSTEM "jugador.dtd">
<jugador>
  <dades_personals>
    <nom></nom>  
    <cognoms></cognoms>
  </dades_personals>
  <fitxa_tecnica>
    <equip></equip>
    <posicio></posicio>
    <dorsal></dorsal>
  </fitxa_tecnica>
  <estadistiques jornada="1">
    <convocat></convocat>
    <minuts_jugats></minuts_jugats>
    <gols></gols>
  </estadistiques>
    <estadistiques jornada="2">
    <convocat></convocat>
    <minuts_jugats></minuts_jugats>
    <gols></gols>
  </estadistiques>
    <estadistiques jornada="3">
    <convocat></convocat>
    <minuts_jugats></minuts_jugats>
    <gols></gols>
  </estadistiques>
    <estadistiques jornada="4">
    <convocat></convocat>
    <minuts_jugats></minuts_jugats>
    <gols></gols>
  </estadistiques>
</jugador>
