=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/documents-export-2016-01-10/navidad.dtd
<!ELEMENT botiga (categories,articles)>
<!ELEMENT categories (categoria+)>
<!ELEMENT categoria (nom, descripcio)>
<!ATTLIST categoria idcat ID #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT articles (article+)>
<!ELEMENT article (nom, descripcio, preu)>
<!ATTLIST article idart ID #REQUIRED idrcat IDREFS #REQUIRED>
<!ELEMENT preu (#PCDATA)>

=== KeshiKiD03/AplicacionesWeb-m09/APUNTES - M04 - Lenguaje de Marcas/M04 - Lenguaje de marcas/UF1 Programación con XML/XML/documents-export-2016-01-10/jer_nav.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE botiga SYSTEM "navidad.dtd">
<botiga>
  <categories>
    <categoria idcat="c01">
      <nom>peix</nom>
      <descripcio>peix que es troba ....</descripcio>
    </categoria>
  <!--   Article:-->
  <!--            Identificador d'article:-->
  <!--            Rferencia categoria:-->
  <!--            Nom:-->
  <!--            Descripcio/preu:-->

  <!--   Categoria:-->
  <!--            Identificador de categoia:-->
  <!--            Nom:-->
  <!--            Descripcio:-->
      <categoria idcat="c02">
      <nom>carn</nom>
      <descripcio>carn que es troba ....</descripcio>
    </categoria>
  </categories>
  <articles>
    <article idart="a01" idrcat="c01">
      <nom>roig</nom>
      <descripcio>de riu</descripcio>
      <preu>11</preu>
    </article>
    
    <article idart="a02" idrcat="c02">
      <nom>tendre</nom>
      <descripcio>fresca</descripcio>
      <preu>5</preu>
    </article>
  </articles>
</botiga>
